test android key directory

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,7 +20,6 @@ jobs:
           if [[ "${GITHUB_REF}" =~ ^refs\/tags\/v* ]]; then
               BUILD_MODE='release'
           fi
-
           echo "Build mode: ${BUILD_MODE}"
           echo "BUILD_MODE=${BUILD_MODE}" >> $GITHUB_ENV
 
@@ -45,40 +44,45 @@ jobs:
           SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
           SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
 
-      - name: Ensure android directory exists
-        run: mkdir -p android
-
       - name: Generate Android key store file
         if: ${{ env.BUILD_MODE == 'release' }}
-        run: |
-          mkdir -p android
-          echo "${SIGNING_KEY}" | base64 -d > android/key.jks
+        run: echo "${SIGNING_KEY}" | openssl base64 -d -out key.jks
         working-directory: ${{ github.workspace }}/android
         env:
           SIGNING_KEY: ${{ secrets.AndroidSigningKeyBase64 }}
 
-
       - name: Verify key.jks file
         if: ${{ env.BUILD_MODE == 'release' }}
-        run: ls -lah android/key.jks
+        run: |
+          if [ -f key.jks ]; then
+            echo "key.jks file generated successfully."
+          else
+            echo "key.jks file is missing!" && exit 1
+          fi
+        working-directory: ${{ github.workspace }}/android
 
       - name: Generate Android key.properties file
         if: ${{ env.BUILD_MODE == 'release' }}
         run: |
-          echo "storeFile=key.jks" > android/key.properties
-          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
-          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
-          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
-
-      - name: Debug Signing Key
-        run: |
-          echo "Signing key length: ${#SIGNING_KEY}"
+          echo "storePassword=${STORE_PASSWORD}" >> key.properties
+          echo "keyPassword=${KEY_PASSWORD}" >> key.properties
+          echo "keyAlias=${KEY_ALIAS}" >> key.properties
+          echo "storeFile=../key.jks" >> key.properties
+        working-directory: ${{ github.workspace }}/android
         env:
-          SIGNING_KEY: ${{ secrets.AndroidSigningKeyBase64 }}
+          STORE_PASSWORD: ${{ secrets.AndroidStorePassword }}
+          KEY_PASSWORD: ${{ secrets.AndroidKeyPassword }}
+          KEY_ALIAS: ${{ secrets.AndroidKeyAlias }}
 
       - name: Verify key.properties file
         if: ${{ env.BUILD_MODE == 'release' }}
-        run: cat android/key.properties
+        run: |
+          if [ -f key.properties ]; then
+            echo "key.properties file generated successfully."
+          else
+            echo "key.properties file is missing!" && exit 1
+          fi
+        working-directory: ${{ github.workspace }}/android
 
       - name: Build Android packages
         run: |
@@ -89,23 +93,32 @@ jobs:
 
       - name: Verify APK signature
         if: ${{ env.BUILD_MODE == 'release' }}
-        run: jarsigner -verify -verbose -certs build/app/outputs/apk/release/app-arm64-v8a-release.apk
+        run: |
+          for apk in build/app/outputs/apk/release/*.apk; do
+            jarsigner -verify -verbose -certs $apk || exit 1
+          done
 
       - name: List APKs and AAB in release folder
         if: ${{ env.BUILD_MODE == 'release' }}
         run: |
-          mkdir -p android_release/apk/release
-          mkdir -p android_release/bundle/release
-          cp build/app/outputs/apk/release/*.apk android_release/apk/release/
-          cp build/app/outputs/bundle/release/*.aab android_release/bundle/release/
-          zip -r android_release.zip android_release
+          ls -R build/app/outputs/apk/release/
+          ls -R build/app/outputs/bundle/release/
 
-      - name: Upload ZIP as artifact
+      - name: Upload Android release artifacts
         if: ${{ env.BUILD_MODE == 'release' }}
         uses: actions/upload-artifact@v4
         with:
-          name: android_release_zip
-          path: android_release.zip
+          name: android_release
+          path: |
+            build/app/outputs/apk/release/*.apk
+            build/app/outputs/bundle/release/*.aab
+
+      - name: Upload Android debug artifacts
+        if: ${{ env.BUILD_MODE == 'debug' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: android_debug
+          path: build/app/outputs/apk/debug/*.apk
 
   release:
     runs-on: ubuntu-latest
@@ -118,19 +131,19 @@ jobs:
       - name: Download Android release artifacts
         uses: actions/download-artifact@v4
         with:
-          name: android_release_zip
-          path: ./
+          name: android_release
+          path: ./android_release
 
-      - name: Extract ZIP file
-        run: unzip android_release.zip
+      - name: List downloaded artifacts
+        run: ls -R ./android_release
 
-      - name: Upload APK and AAB files to GitHub Release
+      - name: Upload artifacts to GitHub Release
         uses: ncipollo/release-action@v1
         with:
           allowUpdates: true
           artifacts: |
-            android_release/apk/release/*.apk
-            android_release/bundle/release/*.aab
+            ./android_release/*.apk
+            ./android_release/*.aab
           name: Release ${{ env.VERSION_STR }}
           prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
           tag: ${{ env.VERSION_STR }}
